server:
  port: 2223
spring:
  application:
    name: service-B


# 用于注册服务
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 由于 eurake 项目添加了验证信息，地址信息需要与
      defaultZone: http://admin:qwe123@localhost:8761/eureka
  instance:
    ip-address: true