
server:
  port: 5555

spring:
  profiles:
    active: @profileActive@

  application:
    name: api-gateway

# 用于注册服务
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 由于 eurake 项目添加了验证信息，地址信息需要与
      defaultZone: http://admin:qwe123@localhost:8761/eureka
  instance:
    ip-address: true


mybatis:
  type-aliases-package: com.lianjia.mls.datakeeper.housedel.model;com.lianjia.common.typehandlers.alias
  type-handlers-package: com.lianjia.common.typehandlers.type
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/complex/*.xml
  check-config-location: false
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: executableSql.
    map-underscore-to-camel-case: true


zuul:
  routes:
    # 直接通过 url 映射转发
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:2222/


    # 通过 微服务 serviceId 的方式来映射
    api-a:
      path: /api-a/**
      serviceId: service-A
    api-b:
      path: /api-b/**
      serviceId: service-B
    product-sidecar:
      path: /product-sidecar/**
      serviceId: product-sidecar


