server:
  port: 2001

spring:
  application:
    name: product-sidecar



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 由于 eurake 项目添加了验证信息，地址信息需要与
      defaultZone: http://admin:qwe123@localhost:8761/eureka

sidecar:
  instance:
    host: 10.33.64.180
  port: 63340
  health-uri: http://${sidecar.instance.host}:${sidecar.port}/testphp/health.json

